services:
  - type: web
    name: aiconsult-hub
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      cd client && npx vite build --outDir ../dist/public && cd ..
      npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /